# Generated by Django 3.0 on 2019-12-31 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(choices=[('QUEUE', 'Queue'), ('RESERVE', 'Reserve'), ('CHAT', 'Chat')], default='QUEUE', max_length=10)),
                ('status', models.CharField(choices=[('QUEUE', 'Queue'), ('RESERVE', 'Reserve'), ('CHAT', 'Chat')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('QUEUE', 'Queue'), ('RESERVE', 'Reserve'), ('CHAT', 'Chat')], default='ACTIVE', max_length=10)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.PatientQueue')),
            ],
        ),
    ]
